#!/bin/bash

## Copyright (C) 2024 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail
shopt -s inherit_errexit
shopt -s shift_verbose
export LC_ALL=C

kernel_cmdline=''
if [ -f /proc/cmdline ]; then
  kernel_cmdline="$(cat -- /proc/cmdline)"
elif [ -f /proc/1/cmdline ]; then
  kernel_cmdline="$(cat -- /proc/1/cmdline)"
fi

# shellcheck disable=SC2076  ## intentional literal substring match
if [[ "${kernel_cmdline}" =~ 'boot-role=unrestricted-admin' ]]; then
   # shellcheck disable=SC2076  ## intentional literal substring match
   if ! [[ "${kernel_cmdline}" =~ 'rd.live.image' ]]; then
      printf '%s\n' 'ERROR: Cannot boot in unrestricted admin mode unless on a live ISO!'
      exit 1
   fi

   dummy-dependency --purge --yes user-sysmaint-split
fi
